### ISSUE TITLE
Minimum system requirements not listed

### ISSUE THREAD

**Issue by polezhaevdmi** [LibRaw/DOFCalc#1]
Hi!
Please, list the minimal system requirements for that application in 'readme file'. 
At least, the CAT S30 with Android 5.1 is not able to install DOFCalc due to 'syntax error' during installation package analysis.
Anyway, greetings with excellent idea implementation!

**Comment by LibRaw** [comment]
Yes, minimal Android version for pre-built APK is Android 6.

BTW, you can build the app yourself for ~any android (tested with 2.3 on emulator), although you'll need some (very) old NDK
